### ISSUE TITLE
2.29 Angular User Admin App: ER Stream #3851

### ISSUE THREAD

**Issue by DavidNesbitt** [pepfar-datim/datim-user-management-ng#138]
Putting placeholder in this repo for work on https://github.com/pepfar-datim/Global/issues/3851

**Comment by jakub-bao** [comment]
Original post from @hardingt 

So IAs are a weird user type here:
They are not allowed to interact with ER, but they are allowed to create Partner users, which ARE allowed to interact with ER stream.

Because of this, the IA user needs to be able to assign ER as a stream to a new Partner user, as well as Data Entry ER.

![image](https://user-images.githubusercontent.com/11567315/44671907-cb234200-a9f4-11e8-9a5d-41a2ce00b30f.png)

When an IA UA user tries to make such a partner, they are given access to Data Entry ER, but not ER as a stream.

**Comment by jakub-bao** [comment]
Per discussion with @hkim224 
We should not do this in the user app but rather on backend... ?

**Comment by jakub-bao** [comment]
![image](https://user-images.githubusercontent.com/47790868/56375050-87bf5300-61d2-11e9-8f5d-cddfa42c5631.png)

**Comment by hkim224** [comment]
Just to confirm - there should be no ability in the User Admin app to confer ER privileges to IA users. This is a very special case that should only be managed by the DATIM team.
