### ISSUE TITLE
`Global` user can see all users

### ISSUE THREAD

**Issue by jakub-bao** [pepfar-datim/datim-user-management-ng#158]
For most of user types: users can see only users they can manage.

E.g. `Partner` user from `OU Angola` can see only `Partners` from `OU Angola`. They shouldn't see `Agency` users from `OU Angola` or `Partner` users from `OU Botswana`

This rule is enforced for all user types except `Global` user.

`Global` users can see everyone else in the system.

This actually seems to be something with DHIS2 backend.

Example:

`API` call as `Partner` (note `total 11`)
```
$ curl https://dev-jakub.datim.org/api/29/users?canManage=true --user cypress-partner:[redacted]
{"pager":{"page":1,"pageCount":1,"total":11,"pageSize":50}
```

`API` call as `Global` (note `total 22132`)
```
$ curl https://dev-jakub.datim.org/api/29/users?canManage=true --user cypress-global:[redacted]
{"pager":{"page":1,"pageCount":443,"total":22132,"pageSize":50,"nextPage":
```

However, this might be wrong. Per @hkim224 `Global` users should see only `Global` users. Not let's say `Agency HQ` user from `Angola`.. True or Wrong?

**Comment by benguaraldi** [comment]
It turns out that `canManage` only verifies that a user administrator can edit users based on the group relationships.  It doesn't verify that the a user administrator can edit a user based on roles.

Maybe a good solution would be to filter the users list based on which users are Global if a user administrator is a Global user and not a superuser?
