### ISSUE TITLE
Slow Searches: Proof of concept a SQL View

### ISSUE THREAD

**Issue by hardingt** [pepfar-datim/datim-user-management-ng#230]
Req: Proof of concept SQL view that is:
1. Security Trimmed by requesting user (is that possible?)
2. Only visible to user admins
3. Allows for one or two additional search types filters
   - User in xyz group
   - username like abc

Questions to answer:
1. Is it fast enough? I should be able to search for users of a type and get some kind of response in under 5 seconds
2. Is it secure enough? By opening up this sql view to all user admins, does it allow for data mining?
3. Is is expandable to many different search clauses?

**Comment by benguaraldi** [comment]
@hardingt I believe this will need to wait for this Jira ticket:
https://jira.dhis2.org/browse/DHIS2-7742

**Comment by hardingt** [comment]
@benguaraldi to be properly security trimmed you betcha!

**Comment by jimgrace** [comment]
Jira ticket [DHIS2-7742](https://jira.dhis2.org/browse/DHIS2-7742) is technically still in review, but for practical purposes it's done. It allows for security trimming by using the internal userid (database foreign key) in a query-type SQL View. I've also (quietly but with permission) ported the feature back to the latest builds of 2.33. (It didn't make it in time for patch release 2.33.1.) If we decide to upgrade to 2.32 rather than 2.33, I could port it back there as well.

Documentation can be found [here](https://docs.dhis2.org/master/en/developer/html/dhis2_developer_manual_full.html#webapi_sql_view_variables).

**Comment by hardingt** [comment]
That's awesome Jim
I wonder, does it gracefully fall back or warn a user if they try to make a view externally accessible? I mean, it doesn't make sense to have a sqlview be public to the world AND try to use the nonexistent userid.

**Comment by jimgrace** [comment]
Good question, Tim. The code may not be as graceful as possible, but at least it checks to prevent a null pointer error in such a circumstance. If there is no current user, the code does not do the substitutions for userid or username.

So if these special variables are used in a query, and the query is made externally accessible, then the SQL might be executed with something like `where um.userinfoid = ${_current_user_id}`, which will cause an error in SQL execution.

As you say, this would be the result of an nonsensical deployment.

**Comment by benguaraldi** [comment]
This is OBE with recent changes that @jakub-bao made to the search functionality.  Closing.
